#!/usr/bin/env bash
# =============================================================================
# 09-write-files.sh — Write .env, docker-compose.yml, nginx confs, upgrade.sh
# Sourced by install.sh — do not execute directly.
# =============================================================================

# -----------------------------------------------------------------------------
# .env
# -----------------------------------------------------------------------------
info "Writing ${INSTALL_DIR}/.env ..."
cat > "${INSTALL_DIR}/.env" <<EOF
# GoSecureShare — Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# ⚠ KEEP THIS FILE SECURE. chmod 600 is set automatically.
# ⚠ Never change ENCRYPTION_KEY after first launch — all stored secrets use it.

GSS_INSTALLED_VERSION=${VERSION}
GSS_INSTALLED_REF=${GIT_REF}
GSS_NAMESPACE=${NAMESPACE}

POSTGRES_HOST=gosecureshare-postgres
POSTGRES_PORT=5432
POSTGRES_DB=gosecureshare
POSTGRES_USER=gss_superuser
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DB_HOST_PORT=5434

GSS_PLATFORM_DB_USER=gss_platform_user
GSS_PLATFORM_DB_PASSWORD=${GSS_PLATFORM_DB_PASSWORD}
GSS_RECIPIENT_DB_USER=gss_recipient_user
GSS_RECIPIENT_DB_PASSWORD=${GSS_RECIPIENT_DB_PASSWORD}

DATABASE_SUPERUSER_URL=postgresql+asyncpg://gss_superuser:${POSTGRES_PASSWORD}@postgres:5432/gosecureshare

ENCRYPTION_KEY=${ENCRYPTION_KEY}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRE_MINUTES=480

GSS_ADMIN_EMAIL=${GSS_ADMIN_EMAIL}
GSS_ADMIN_PASSWORD=${GSS_ADMIN_PASSWORD}
ADMIN_EMAIL=${GSS_ADMIN_EMAIL}
ADMIN_HASHED_PASSWORD=${ADMIN_HASHED_PASSWORD_ESC}

CORS_ORIGINS_RAW=*
PLATFORM_DOMAIN=${PLATFORM_DOMAIN}
RECIPIENT_DOMAIN=${RECIPIENT_DOMAIN}
PLATFORM_HTTP_PORT=${PLATFORM_HTTP_PORT}
RECIPIENT_HTTP_PORT=${RECIPIENT_HTTP_PORT}

DEBUG=false
ENABLE_SWAGGER=false
GSS_DEV_AUTO_RESET_DB=false

LDAP_ENABLED=false
LDAP_URL=
LDAP_BASE_DN=
LDAP_BIND_DN=
LDAP_BIND_PASSWORD=
EOF
chmod 600 "${INSTALL_DIR}/.env"
success ".env written and secured (chmod 600)."

# -----------------------------------------------------------------------------
# docker-compose.yml
# -----------------------------------------------------------------------------
info "Writing ${INSTALL_DIR}/docker-compose.yml (images: ghcr.io/${NAMESPACE}/*, tag: ${VERSION})..."
cat > "${INSTALL_DIR}/docker-compose.yml" <<EOF
services:
  postgres:
    image: postgres:16-alpine
    container_name: gosecureshare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${POSTGRES_DB}
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - gss_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gss_internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  db-migrate:
    image: postgres:16-alpine
    container_name: gosecureshare-db-migrate
    restart: on-failure
    env_file: .env
    environment:
      PGPASSWORD: \${POSTGRES_PASSWORD}
      ADMIN_EMAIL: \${ADMIN_EMAIL}
      ADMIN_HASHED_PASSWORD: \${ADMIN_HASHED_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gss_internal
    volumes:
      - ./db/docker-migrate.sh:/docker-migrate.sh:ro
    entrypoint: ["/bin/sh", "/docker-migrate.sh"]

  api_platform:
    image: ${TAGGED_API_PLATFORM}
    container_name: gosecureshare-api-platform
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ROLE: platform
      DATABASE_URL: postgresql+asyncpg://\${GSS_PLATFORM_DB_USER}:\${GSS_PLATFORM_DB_PASSWORD}@postgres:5432/\${POSTGRES_DB}
      DATABASE_SUPERUSER_URL: postgresql+asyncpg://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    networks:
      - gss_internal
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 60s

  api_recipient:
    image: ${TAGGED_API_RECIPIENT}
    container_name: gosecureshare-api-recipient
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ROLE: recipient
      DATABASE_URL: postgresql+asyncpg://\${GSS_RECIPIENT_DB_USER}:\${GSS_RECIPIENT_DB_PASSWORD}@postgres:5432/\${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    networks:
      - gss_internal
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/ping"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

  nextjs_platform:
    image: ${TAGGED_FRONTEND_PLATFORM}
    container_name: gosecureshare-ui-platform
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://api_platform:8000
    depends_on:
      api_platform:
        condition: service_healthy
    networks:
      - gss_internal
    expose:
      - "3000"

  nextjs_recipient:
    image: ${TAGGED_FRONTEND_RECIPIENT}
    container_name: gosecureshare-ui-recipient
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_RECIPIENT_API_URL: http://api_recipient:8000
    depends_on:
        api_recipient:
          condition: service_healthy
    networks:
      - gss_internal
    expose:
      - "3000"

  nginx_platform:
    image: nginx:1.27-alpine
    container_name: gosecureshare-nginx-platform
    restart: unless-stopped
    ports:
      - "${PLATFORM_BIND}:80"
    volumes:
      - ./nginx/platform.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs_platform
      - api_platform
    networks:
      - gss_internal

  nginx_recipient:
    image: nginx:1.27-alpine
    container_name: gosecureshare-nginx-recipient
    restart: unless-stopped
    ports:
      - "${RECIPIENT_BIND}:80"
    volumes:
      - ./nginx/recipient.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs_recipient
      - api_recipient
    networks:
      - gss_internal

networks:
  gss_internal:
    driver: bridge

volumes:
  gss_pgdata:
EOF
success "docker-compose.yml written."

# -----------------------------------------------------------------------------
# Nginx reverse proxy configs (inside Docker)
# -----------------------------------------------------------------------------
info "Writing Nginx reverse proxy configs..."
cat > "${INSTALL_DIR}/nginx/platform.conf" <<'NGINXEOF'
upstream platform_api { server api_platform:8000; }
upstream platform_ui  { server nextjs_platform:3000; }
server {
    listen 80;
    client_max_body_size 50M;
    location /api/          { proxy_pass http://platform_api; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; }
    location /healthz        { proxy_pass http://platform_api; proxy_set_header Host $host; }
    location /api/docs       { return 404; }
    location /openapi.json   { return 404; }
    location /               { proxy_pass http://platform_ui;  proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; }
}
NGINXEOF

cat > "${INSTALL_DIR}/nginx/recipient.conf" <<'NGINXEOF'
upstream recipient_api { server api_recipient:8000; }
upstream recipient_ui  { server nextjs_recipient:3000; }
server {
    listen 80;
    client_max_body_size 50M;
    location /api/          { proxy_pass http://recipient_api; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; }
    location /api/docs       { return 404; }
    location /openapi.json   { return 404; }
    location /               { proxy_pass http://recipient_ui;  proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; }
}
NGINXEOF
success "Nginx configs written."

# -----------------------------------------------------------------------------
# upgrade.sh
# -----------------------------------------------------------------------------
info "Writing ${INSTALL_DIR}/upgrade.sh ..."
cat > "${INSTALL_DIR}/upgrade.sh" <<'UPGRADEEOF'
#!/usr/bin/env bash
set -euo pipefail
GITHUB_REPO="kisa-ops/GoSecureShare"
NAMESPACE="kisa-ops"
REGISTRY="ghcr.io"
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
[[ $EUID -ne 0 ]] && error "Please run as root: sudo ./upgrade.sh"
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${INSTALL_DIR}/.env"
[[ -f "${ENV_FILE}" ]] || error "No .env found at ${ENV_FILE}. Is GoSecureShare installed?"
CURRENT_VERSION=$(grep '^GSS_INSTALLED_VERSION=' "${ENV_FILE}" 2>/dev/null | cut -d= -f2 || echo "unknown")
if [[ -n "${1:-}" ]]; then
  TARGET_VERSION="${1#v}"
else
  info "Checking latest release..."
  curl_auth=()
  [[ -n "${GHCR_TOKEN:-}" ]] && curl_auth=(-H "Authorization: Bearer ${GHCR_TOKEN}")
  TARGET_VERSION=$(curl -fsSL --connect-timeout 8 \
    -H "Accept: application/vnd.github+json" \
    "${curl_auth[@]}" \
    "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" 2>/dev/null \
    | grep '"tag_name"' \
    | sed 's/.*"tag_name": "\(.*\)".*/\1/' \
    | tr -d '[:space:]' \
    | sed 's/^v//' || echo "")
  [[ -z "${TARGET_VERSION}" || ! "${TARGET_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && \
    error "Could not resolve latest release. Specify manually: sudo ./upgrade.sh 2.5.0"
fi
if [[ "${CURRENT_VERSION}" == "${TARGET_VERSION}" ]]; then
  info "Already on version ${TARGET_VERSION}. Nothing to do."
  exit 0
fi
echo -e "  ${YELLOW}${BOLD}Upgrading ${CURRENT_VERSION} → ${TARGET_VERSION}. Proceed? (type 'yes'): ${RESET}"
read -r _confirm
[[ "${_confirm}" == "yes" ]] || { info "Aborted."; exit 0; }
if [[ -n "${GHCR_USERNAME:-}" && -n "${GHCR_TOKEN:-}" ]]; then
  info "Logging in to GHCR as ${GHCR_USERNAME}..."
  echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin || error "GHCR login failed."
fi
IMAGES=("gosecureshare-api-platform" "gosecureshare-api-recipient" "gosecureshare-frontend-platform" "gosecureshare-frontend-recipient")
for img in "${IMAGES[@]}"; do
  docker pull "${REGISTRY}/${NAMESPACE}/${img}:${TARGET_VERSION}" || error "Failed to pull ${img}:${TARGET_VERSION}"
done
for img in "${IMAGES[@]}"; do
  sed -i "s|${REGISTRY}/${NAMESPACE}/${img}:.*|${REGISTRY}/${NAMESPACE}/${img}:${TARGET_VERSION}|g" \
    "${INSTALL_DIR}/docker-compose.yml"
done
cd "${INSTALL_DIR}"
docker compose up -d
sed -i "s|^GSS_INSTALLED_VERSION=.*|GSS_INSTALLED_VERSION=${TARGET_VERSION}|" "${ENV_FILE}"
success "Upgrade complete: ${CURRENT_VERSION} → ${TARGET_VERSION}"
UPGRADEEOF
chmod +x "${INSTALL_DIR}/upgrade.sh"
success "upgrade.sh written."
